### ISSUE TITLE
Redução de Strings

### ISSUE THREAD

**Issue by renanmms** [NET-Devs-BR/desafios-string#7]
**Título:**  Redução de Strings
**Enunciado:** Reduza uma string `s` com caracteres minúsculos no intervalo de `ascii[a..z]` realizando uma série de operações. Em cada operação, selecione o par de letras adjacentes que são iguais, e remova-os. Se após as operações a string `s` ficar vazia, retornar `'String Vazia'`.

## Restrições

- `1 <= tamanho de s <= 100`

## Casos de teste

Segue abaixo, exemplos de entrada e saída do nosso problema:

### Entrada 1
> aab

### Saída 1
> b

# 

### Entrada 2
> abba

### Saída 2
> 'String Vazia'

# 

### Entrada 3
> blzz

### Saída 3
> bl

**Comment by luisdeol** [comment]
Muito obrigado pela contribuição, @renanmms !
